version: '3'

services:
  dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: vikash
      MYSQL_PASSWORD: pass

  drupalos:
    image: drupal:8.0-apache
    restart: always
    ports:
      - 8085:80
    volumes:
      - drupal_storage_modules:/var/www/html/modules
      - drupal_storage_profiles:/var/www/html/profiles
      - drupal_storage_sites:/var/www/html/sites
      - drupal_storage_themes:/var/www/html/themes
volumes:
    drupal_storage_modules:
    drupal_storage_profiles:
    drupal_storage_sites:
    drupal_storage_themes:
    mysql_storage:
