version: '3'

services:
  dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: vikash
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: mydb

  wordpressos:
    image: wordpress:5.1.1-php7.3-apache
    restart: always
    depends_on:
      - dbos
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: vikash
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wp_storage:/var/www/html

volumes:
    wp_storage:
    mysql_storage:
